### ISSUE TITLE
怎么支持多个目录上传呢。

### ISSUE THREAD

**Issue by itxuye** [yingye/qcloud-upload#1]
请问支持多个目录和其他目录单个文件同时上传吗

**Comment by itxuye** [comment]
```
  prefix: 'A',
  dirPath: path.resolve(__dirname, './B'),
  distDirName: '',
  overWrite: true,
```
我想把B目录下的所有文件传到A目录下，distDirName应该写啥，现在不写会把整个路径填上去，但是现在不想生成子目录，只想把B目录下的文件传到A根目录下

**Comment by yingye** [comment]
distDirName，写'B'就可以。
```
prefix: 'A',
dirPath: path.resolve(__dirname, './B'),
distDirName: 'B',
overWrite: true,
```
摘自README的介绍：
`distDirName(string)`:  截取文件路径参考项，以本项目 examples 文件夹为例，不设置该项，上传腾讯云后文件路径为 https://static.demo.com/your-options.prefix/Users/yingye/Desktop/qcloud-upload/examples/img.png 。若设置该项 `distDirName: 'examples' `后，文件URL为 https://static.demo.com/your-options.prefix/examples/img.png ，相当于对 `dirPath` 绝对路径做了截取操作。

**Comment by itxuye** [comment]
@yingye  distDirName: 'B',但是prefix要写 '',这个已经好了
